### ISSUE TITLE
Groups, Expandable Collapsible groups

### ISSUE THREAD

**Issue by botev** [strathausen/dracula#37]
So, I don't know if this is on your roadmap, but many libraries for graph lack this functionality and in many cases where we have some hierarchy in large graphs such features are a must. Just to explain in more details:

Allow nodes to be assigned to groups, and groups to be assignable to other groups as well to form hierarchies. Allow easy to collapse/expand groups to a single node. 

Sorry I can't help with this, but really I am not experienced in js.

**Comment by nicopace** [comment]
any news on this?

**Comment by strathausen** [comment]
I'm thinking about how to make the graph display more dynamic, like removing and adding nodes... this ticket would definitely part of it once I find a nice solution.

**Comment by monomon** [comment]
@botev do you perhaps mean [Raphael sets](http://dmitrybaranovskiy.github.io/raphael/reference.html#Set)? This seems to fit your description, though they do not use svg <g> elements underneath.

**Comment by monomon** [comment]
I would like to give this ticket a try.

The logical flow is - if there is a series of nodes connected by directed edges, then allow collapsing all nodes "downstream", e.g. by clicking the node. This seems like a clear enough convention.

A more advanced version could allow nodes that are "tagged" to be hidden, regardless of where in tree they are in (i.e. might not have a hierarchical relation).

Implementing this sort of depends on preserving layout between redraws, which is https://github.com/strathausen/dracula/issues/10

Otherwise it would feel very weird that the updated graph would be completely re-laid out.

**Comment by strathausen** [comment]
I added this feature request to the list https://github.com/strathausen/dracula/projects/1
